# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'DevOps'
variables:
- name: first
  value: initialvalue
- group : TokenDetails


stages:
- stage: BuildApp
  displayName: Build Apps
  jobs:
  - job: BuildFrontendApp
    displayName: Build Frontend App
    steps:
    - task: CmdLine@2
      inputs:
          script: |
            echo Write your commands here
            echo Hello world
            echo $(Build.SourcesDirectory)
            echo "$(Build.SourcesDirectory)"
            echo "$(Build.BuildId)"
            echo "$(Build.SourceBranch)"
            echo "$(Build.Reason)"
            echo "$(Build.DefinitionName)"
            echo "$(Build.SourceVersion)"
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          Write-Host "Hello World"

  - job: BuildBackendApp
    displayName: Build Backend App
    steps:
    - script: echo building backend app
      displayName: build backend app
    - script: echo running unit tests for backend app
      displayName: unit tests backend

- stage: DeployDev
  displayName: Deploy to DEV environment
  jobs:
  - job: DeployFrontendDev
    displayName: Deploy frontend to DEV
    steps:
    - script: echo deploying frontend app to DEV
      displayName: deploy frontend app to DEV

  - job: DeployBackendDev
    displayName: Deploy backend to DEV
    steps:
    - script: echo deploying backend app to DEV
      displayName: deploy backend app to DEV

- stage: DeployProd
  displayName: Deploy to PROD environment
  pool:
    name: 'DevOps'
  jobs:
  - job: DeployFrontendProd
    displayName: Deploy frontend to PROD
    steps:
    - script: echo deploying frontend app to PROD
      displayName: deploy frontend app to PROD

  - job: DeployBackendProd
    displayName: Deploy backend to PROD
    pool:
      name: DevOps
    steps:
    - script: |
        echo deploying backend app to PROD
        echo Write your commands here
        echo Hello world
        echo $(Token)
        echo $(first)
        echo $(Az_Token)
        echo $(username)
      displayName: deploy backend app to PROD

